In [1]:
import numpy as np

# **MATRICES**

### Definiendo matrices

In [8]:
R = np.array([[0,1,0],[0,0,1]])
R

array([[0, 1, 0],
       [0, 0, 1]])

In [15]:
beta = np.array([[-1.5789474],[0.96491228],[0.56140351]])
beta

array([[-1.5789474 ],
       [ 0.96491228],
       [ 0.56140351]])

In [23]:
x_x = np.array([[0.96,-0.1,-0.13],[-0.1,0.11,-0.05],[-0.13,-0.05,0.068]])
x_x

array([[ 0.96 , -0.1  , -0.13 ],
       [-0.1  ,  0.11 , -0.05 ],
       [-0.13 , -0.05 ,  0.068]])

### Multiplicacion de matrices: @

In [16]:
a = R@beta
a

array([[0.96491228],
       [0.56140351]])

### Transpuesta de una matriz: " *np.transpose* "

In [22]:
np.transpose(a)

array([[0.96491228, 0.56140351]])

In [20]:
m=np.array([[3,4,-1],[2,0,1],[1,3,-2]])

### Inversa de una matriz: " *np.linalg.inv* "

In [21]:
np.linalg.inv(m)

array([[-0.6,  1. ,  0.8],
       [ 1. , -1. , -1. ],
       [ 1.2, -1. , -1.6]])

In [26]:
a =np.transpose(R@beta)
a

array([[0.96491228, 0.56140351]])

In [36]:
b = np.linalg.inv(R@x_x@np.transpose(R))
b

array([[13.65461847, 10.04016064],
       [10.04016064, 22.08835341]])

In [30]:
c = R@beta
c

array([[0.96491228],
       [0.56140351]])

In [37]:
print((a@b@c)/2/(7.157894/4))

[[8.53672777]]


In [40]:
print((np.transpose(R@beta)@np.linalg.inv(R@x_x@np.transpose(R))@R@beta)/2/(7.1574894/4))

[[8.53721034]]
